description: Helm chart for the HMCTS CCD Case Management
name: ccd-case-management-web
apiVersion: v1
home: https://github.com/hmcts/ccd-case-management-web
version: 2.0.5
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
