nodejs:
  image: hmcts.azurecr.io/hmcts/ccd-case-management-web:latest
  applicationPort: 3451
  memoryRequests: 256Mi
  cpuRequests: 25m
  memoryLimits: 512Mi
  cpuLimits: 1
  environment:
    CCD_GW_OAUTH2_CLIENT_ID: ccd_gateway
    CCD_PAGE_SIZE: 25
    CCD_ACTIVITY_NEXT_POLL_REQUEST_MS: 5000
    CCD_ACTIVITY_RETRY: 5
    CCD_ACTIVITY_BATCH_COLLECTION_DELAY_MS: 1
    CCD_ACTIVITY_MAX_REQUEST_PER_BATCH: 25

